Edgex 289 e kuiper snap separated from the edgexfoundry snap
MonicaisHer/edgex-ekuiper-snap pull request #2
Opened 2022-02-11 14:35 UTC by MonicaisHer

2022-02-21 09:49 UTC, farshidtz commented
The hardcoded config can be set once during the build. I suggest you place the whole yaml file in the source code and replace the original one with it during the build.

The username, password can be queried from vault and injected into the config file as soon as the vault token is copied over via the content interface. You can do that in a connect hook: https://snapcraft.io/docs/interface-hooks
Doing so will complicate the logic: if kuiper is installed after edgexfoundry, the connection happens before service starts. But if the order is changed, the kuiper would start without the credentials and the credentials get injected afterwards. Will kuiper watch the config file and react accordingly? Or we would have to restart the service to pick up the new info?

2022-02-22 10:09 UTC, MonicaisHer commented
@farshidtz Thanks for your suggestions. 
if ekuiper is installed before edgexfoundry, the ekuiper would start without the credentials after a maximum 60s retry. 
If the credentials are available within the 60s, ekuiper will automatically pick up it. 
If the credentials are available after the 60s, ekuiper needs a `restart` to pick up new info.

2022-02-22 10:50 UTC, farshidtz reviewed
It's good to have the connect interface and token query in place.

At this point, I'm skeptical about the need of hooks written in Go.

2022-02-22 10:50 UTC, farshidtz commented on snap/snapcraft.yaml
> +      ' $SNAPCRAFT_PART_INSTALL/etc/connections/connection.yaml
Perhaps it would be simpler to supply the expected config file from the source (i.e. this repo) insteading making all this changes to the kuiper source file.

2022-02-22 10:50 UTC, farshidtz commented on snap/local/hooks/cmd/install/install.go
> +	}
This will not capture the standard output. Use https://pkg.go.dev/os/exec#Cmd.CombinedOutput and send the logs to syslog using the hooks library loggers.

2022-02-22 10:50 UTC, farshidtz commented on snap/local/hooks/cmd/install/install.go
> +}
This hook doesn't do anything other than executing `install-setup-kuiper.sh`. The binary adds 3MB to the snap size. Why not place that script directly at snap/hooks/install and remove this go package?

2022-02-22 10:50 UTC, farshidtz commented on snap/local/hooks/cmd/configure/configure.go
> +	}
Does kuiper support env variables?

2022-02-22 10:50 UTC, farshidtz commented on snap/local/hooks/cmd/configure/configure.go
> +	}
Does kuiper support DEBUG environment variable to enable debug logging?

2022-02-22 10:50 UTC, farshidtz commented on snap/hooks/connect-plug-edgex-secretstore-token
> +$SNAP/bin/setup-redis-secrets.sh "connect-plug-edgex-secretstore-token"
If `setup-redis-secrets.sh` is not reused, you can include its content right here and remove `setup-redis-secrets.sh`.

2022-02-22 10:50 UTC, farshidtz commented on snap/snapcraft.yaml
> +      rm *.gz
`real_pkg` or another step also creates a zip file which should be removed.

2022-02-22 10:50 UTC, farshidtz commented on snap/snapcraft.yaml
> +      echo $GIT_VERSION > ./VERSION
is it?

2022-02-22 10:50 UTC, farshidtz commented on snap/local/runtime-helpers/bin/install-setup-kuiper.sh
> +fi
Remove either "setup" or "install" from filename.

I believe the logic can be simplified.
1. You can try using `install` command which automatically created the target directory hierarchy and remove the need for directory creations (mkdir) on top.
2. edgex.json file may not be needed.
3. Remove file pattern when all files are being copied, e.g. `"$SNAP/etc/functions/"*.json`
4. Most of the logic (if not all) need to happen in build instead and not install. We don't wanna package files that we don't need into the snap only to refactor them on install.

2022-02-22 10:50 UTC, farshidtz commented on snap/local/runtime-helpers/bin/security-secret-store-env-var.sh
> +    export EDGEX_SECURITY_SECRET_STORE
Not used right now. But there may be some use for it to control kuiper's connection.

2022-02-22 10:50 UTC, farshidtz commented on snap/local/runtime-helpers/bin/startup-env-var.sh
> +exec "$@"
Are these relevant or needed? Startup interval should be handled by `restart-delay: 60s`.  Does kuiper read kuiper.env file?

2022-02-22 10:50 UTC, farshidtz commented on snap/snapcraft.yaml
> +epoch: 4
epoch should be 0, since we are starting from scratch.
https://snapcraft.io/docs/snap-epochs

2022-02-22 10:50 UTC, farshidtz commented on snap/snapcraft.yaml
> +    adapter: full
remove adapter, `full` is the default value.

2022-02-22 10:55 UTC, farshidtz commented on snap/local/runtime-helpers/bin/install-setup-kuiper.sh
> +fi
Remove either "setup" or "install" from filename.

I believe the logic can be simplified.

You can try using install command which automatically created the target directory hierarchy and remove the need for directory creations (mkdir) on top.
edgex.json file may not be needed.
Remove file pattern when all files are being copied, e.g. "$SNAP/etc/functions/"*.json
Most of the logic (if not all) need to happen in build instead and not install. We don't wanna package files that we don't need into the snap only to refactor them on install.

2022-02-22 10:55 UTC, farshidtz commented on snap/local/runtime-helpers/bin/startup-env-var.sh
> +exec "$@"
Are these relevant or needed? Startup interval should be handled by restart-delay: 60s. Does kuiper read kuiper.env file?

2022-02-22 10:55 UTC, farshidtz commented on snap/local/hooks/cmd/install/install.go
> +}
This hook doesn't do anything other than executing `install-setup-kuiper.sh`. The binary adds 3MB to the snap size. Why not place that script directly at snap/hooks/install and remove this go package?

2022-02-22 13:12 UTC, farshidtz commented
For security, there are two scenarios:
1. Security enabled: Kuiper gets the token, queries redis credentials, starts/restarts. 
2. Security disabled: Kuiper will start without credentials and work as expected. When security is enabled, kuiper would need to be restarted **manually** to use the now available vault token to query redis credentials.

Future work: The security enabling can be automated by watching the files and restarting kuiper automatically.

2022-02-23 08:45 UTC, MonicaisHer commented on snap/snapcraft.yaml
> +      echo $GIT_VERSION > ./VERSION
Yes, please see: https://github.com/lf-edge/ekuiper/blob/master/Makefile#L50-L53

2022-02-23 09:48 UTC, farshidtz commented on snap/snapcraft.yaml
> +      fi
This will fails if the repo (e.g. when forked) has no tag.

Try:
```
if git describe ; then
  GIT_VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
else
  GIT_VERSION="0.0.0"
fi
```

2022-02-23 09:48 UTC, farshidtz commented on snap/local/hooks/cmd/configure/configure.go
> +	autostart, err := cli.Config(hooks.AutostartConfig)
To simulate seeding of the config option, set it before here manually. Or set it in the install hook.

2022-02-23 14:57 UTC, MonicaisHer commented on snap/local/runtime-helpers/bin/install-setup-kuiper.sh
> +fi
connection selector client and edgex message client need `sources/edgex.json`, otherwise:
```
level=error msg="can not create client for connection selector : edgex.redisMsgBus have error open /var/snap/edgex-ekuiper/x1/etc/sources/edgex.json: no such file or directory" file="connection/manager.go:61"
level=error msg="The edgex client for connection selector edgex.redisMsgBus get fail with error: open /var/snap/edgex-ekuiper/x1/etc/sources/edgex.json: no such file or directory" file="source/edgex_source.go:124" source_pool=edgex.stream1
level=error msg="Failed to get edgex message client: open /var/snap/edgex-ekuiper/x1/etc/sources/edgex.json: no such file or directory" file="source/edgex_source.go:148" source_pool=edgex.stream1
```

2022-02-24 08:48 UTC, MonicaisHer commented on snap/local/runtime-helpers/bin/startup-env-var.sh
> +exec "$@"
These are not needed. Kuiper did not read kuiper.env. Removed.  
Do we need to include [`restIp`](https://github.com/MonicaisHer/edgex-ekuiper-snap/blob/EDGEX-289-e-kuiper-snap-separated-from-the-edgexfoundry-snap/etc/kuiper.yaml#L17) here?

2022-02-24 08:52 UTC, farshidtz commented on snap/local/runtime-helpers/bin/startup-env-var.sh
> +exec "$@"
You mean to be able to read a user defined value via `snap get` and inject it into the kuiper.yaml?

2022-02-24 09:03 UTC, MonicaisHer commented on snap/local/runtime-helpers/bin/startup-env-var.sh
> +exec "$@"
yes

2022-02-24 09:10 UTC, farshidtz commented on snap/local/runtime-helpers/bin/startup-env-var.sh
> +exec "$@"
For now, the users can manually edit the config file and restart. Let's leave it as that.

In future versions, we may
- add the ability to override the config files via a config provider
- add the ability to change config items via snap set and yq
(please add internal issues for these)

2022-02-24 10:11 UTC, MonicaisHer commented on snap/local/runtime-helpers/bin/startup-env-var.sh
> +exec "$@"
Thanks, added.

2022-02-24 10:12 UTC, MonicaisHer commented on snap/local/hooks/cmd/configure/configure.go
> +	}
No, removed. DEBUG logging needs to be set in [kuiper.yaml](https://github.com/MonicaisHer/edgex-ekuiper-snap/blob/EDGEX-289-e-kuiper-snap-separated-from-the-edgexfoundry-snap/etc/kuiper.yaml#L3)

2022-02-24 10:13 UTC, MonicaisHer commented on snap/local/hooks/cmd/configure/configure.go
> +	}
No, removed.

2022-02-24 10:21 UTC, farshidtz requested changes

2022-02-24 10:21 UTC, farshidtz commented on snap/local/hooks/cmd/configure/configure.go
> +	case "yes":
```suggestion
	case "true", "yes":
```

2022-02-24 10:21 UTC, farshidtz commented on snap/local/hooks/cmd/configure/configure.go
> +		// no action necessary
```suggestion
	case "false", "no":
		hooks.Debug("edgex-kuiper: autostart is disabled")
```

2022-02-24 10:21 UTC, farshidtz commented on snap/local/hooks/cmd/configure/configure.go
> +	}
Redundant. Already done in case statement.
```suggestion
```

2022-02-24 10:21 UTC, farshidtz commented on snap/local/runtime-helpers/bin/redis-token-setup.sh
> +# check if CURL or YQ return no-zero code
no indentation inside if statement

2022-02-24 10:21 UTC, farshidtz commented on snap/snapcraft.yaml
> +      snapcraftctl set-version ${GIT_VERSION}
Future work:.

`snapcraftctl set-version ${GIT_VERSION}`
We'll have to add snap versioning to the snap for when snap is updated against the same kuiper version.

E.g. `1.4.2+snap.1` from tag of edgex-ekuiper-snap repo.

For separation of concern, this should be done from another part with appropriate adjustments to `adopt-info`.

2022-02-24 10:21 UTC, farshidtz commented on snap/snapcraft.yaml
> +      - -etc/services/
Can you perform zip and gz exclusions the same way?

2022-02-24 10:21 UTC, farshidtz commented on snap/snapcraft.yaml
> +# TODO: add armhf when the project supports this
please remove this comment.

2022-02-24 10:21 UTC, farshidtz commented on snap/local/hooks/cmd/configure/configure.go
> +}
I still think the Go package is overkill, given the added complexity (imports, vendoring, build) and not something we can easily bring to upstream kuiper (because of the edgex-snap-hooks dependency). The above logic can be easily added in a bash script under `snap/hooks/configure`. See https://snapcraft.io/docs/supported-snap-hooks#heading--the-configure-hook

2022-02-24 10:21 UTC, farshidtz commented on snap/local/hooks/cmd/install/install
> +fi
Place this script at `snap/hooks/install`. See https://snapcraft.io/docs/supported-snap-hooks#heading--install

2022-02-24 11:02 UTC, farshidtz commented on snap/local/hooks/cmd/configure/configure.go
> +		// no action necessary
You can instead just try to stop here. It will do nothing it it is already stopped, depending on what is set as `install-mode`.

2022-02-24 11:02 UTC, farshidtz commented on snap/hooks/connect-slot-edgex-secretstore-token
> +logger "edgex-ekuiper: connect-slot-edgex-secretstore-token: connected"
Future work:

Schedule a kuiper restart to pick up the file and connect securely.

2022-02-24 12:37 UTC, farshidtz commented on snap/local/hooks/cmd/configure/configure.go
> +}
Let's just keep install-mode as enabled (default) and remove the configure hook. We can add it later if toggling auto start via config options becomes a requirement.

2022-02-24 15:11 UTC, MonicaisHer commented
@farshidtz @siggiskulason Could you please help me review it? Thanks!

2022-02-25 09:25 UTC, farshidtz commented on snap/local/runtime-helpers/bin/redis-token-setup.sh
> +		exit 1
This needs so refactoring. The query is repeated twice and the errors aren't sent to the logger. 

1) Query once, then process the exit code. If it is non-zero, print the response using logger.
2) Check status code. If not 200, print the body using logger.
3) Process the body using YQ. If exit code not zero, proceed.

Refer to this to read body and http code at the same time, then process them separately:
https://stackoverflow.com/a/37072904/3041544

If query fails, curl will have a non-zero exit code. If query is successful and status code is an error e.g. 400, exit code will be zero.
```
$ curl --write-out "%{http_code}" --silent --show-error -H -X GET http://google.com2 --include
curl: (6) Could not resolve host: GET
curl: (6) Could not resolve host: google.com2
$ echo $?
6
```

2022-02-25 11:20 UTC, farshidtz approved these changes
Thanks a lot for the work.
Please squash and merge with an appropriate commit message.

Other fixes need to be added later, including the addition of copyright notices.

2022-02-25 11:32 UTC, merged